package POJOs;

public enum Symptoms {
    // Motor Symptoms
    TREMOR_REST,
    BRADYKINESIA,
    RIGIDITY,
    POSTURAL_INSTABILITY,
    FREEZING_OF_GAIT,
    SHUFFLING_GAIT,
    MICROGRAPHIA,
    HYPOMIMIA,
    REDUCED_ARM_SWING,
    MOVEMENT_INITIATION_DIFFICULTY,
    TURNING_DIFFICULTY,
    DYSARTHRIA,
    DYSPHAGIA,

    // Secondary Motor Symptoms
    DYSTONIA,
    MUSCLE_CRAMPS,
    FATIGUE,
    SLOW_EYE_MOVEMENTS,
    MUSCULOSKELETAL_PAIN,
    STOOPED_POSTURE,
    DYSKINESIA,

    // Autonomic Symptoms
    ORTHOSTATIC_HYPOTENSION,
    ABNORMAL_SWEATING,
    TEMPERATURE_INTOLERANCE,
    CONSTIPATION,
    URINARY_PROBLEMS,
    SEXUAL_DYSFUNCTION,
    AUTONOMIC_CARDIAC_DYSFUNCTION,

    // Sensory Symptoms
    ANOSMIA,
    GENERAL_PAIN,
    TINGLING,
    PROPRIOCEPTION_ISSUES,

    // Cognitive Symptoms
    EXECUTIVE_DYSFUNCTION,
    BRADYPHRENIA,
    ATTENTION_PROBLEMS,
    MEMORY_PROBLEMS,
    DEMENTIA,

    // Mood Symptoms
    DEPRESSION,
    ANXIETY,
    APATHY,
    IRRITABILITY,

    // Sleep Symptoms
    REM_SLEEP_BEHAVIOR_DISORDER,
    INSOMNIA,
    EXCESSIVE_DAYTIME_SLEEPINESS,
    RESTLESS_LEGS,
    FRAGMENTED_SLEEP,

    // Voice / Speech Symptoms
    HYPOPHONIA,
    MONOTONE_VOICE,
    RAPID_SPEECH,
    ARTICULATION_PROBLEMS
}
